# Welcome to Jekyll!

# Website settings
title: Clark Log
tagline: 'The blog of Clark'
description: 'Clark Blog'
keywords: Clark,Clarkdo,blog,Jekyll,github,gh-pages
baseurl:  / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://clarkdo.github.io/
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: GitHub  # Be used at blog posts' author.
  first_name: Clark  # Be used at index page about me section.
  last_name: Du  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: clarkdo  # Leave blank if you don't have now
  linkedin_id: 欣-杜-29373a95 # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: clark.duxin@gmail.com  # Leave blank if you don't have now
  cv: http://clarkdo.github.com  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-java
    - name: icon-php
  skill_icon2:
    - name: icon-javascript
    - name: icon-nodejs
  desc: I'm clark, an ordinary programmer.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: clarkdo

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

